Feature/436 Added Saturation to User and Appointment
RedSky-Consultancy/LIMS-Server pull request #458
Opened 2021-11-03 11:52 UTC by Narendran2020

2021-11-06 06:30 UTC, Aswathyshibu requested changes

2021-11-06 06:30 UTC, Aswathyshibu commented on LIMS.Business/Injectors/AppointmentInjector.cs
> +            ILimsRepository<Salutation> salutationRepository)
Please fix the alignment

2021-11-06 06:30 UTC, Aswathyshibu commented on LIMS.Business/Injectors/UserInjector.cs
> +            ILimsRepository<Salutation> salutationRepository)
Fix the alignment

2021-11-06 06:30 UTC, Aswathyshibu commented on LIMS.Business/Injectors/UserInjector.cs
> +            this._salutationRepository = salutationRepository;
alignment

2021-11-08 06:45 UTC, Narendran2020 commented on LIMS.Business/Injectors/UserInjector.cs
> +            this._salutationRepository = salutationRepository;
done

2021-11-08 06:45 UTC, Narendran2020 commented on LIMS.Business/Injectors/UserInjector.cs
> +            ILimsRepository<Salutation> salutationRepository)
Done

2021-11-08 06:46 UTC, Narendran2020 commented on LIMS.Business/Injectors/AppointmentInjector.cs
> +            ILimsRepository<Salutation> salutationRepository)
Done

2021-11-08 07:38 UTC, arunselvakumar approved these changes

2021-11-08 07:39 UTC, arunselvakumar commented
Looks good, Approved!

2021-11-08 08:55 UTC, Aswathyshibu approved these changes

2021-11-08 08:56 UTC, merged